version: '3.3'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - 'postgres:/var/lib/postgresql/data'    
  app:
    build: .
    command: rackup config.ru -o 0.0.0.0
    volumes:
      - '.:/usr/src/app'
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      - LANG=C.UTF-8      

volumes:
  postgres: